// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

import {IPoolAddressesProvider, IPool, IPoolConfigurator, IAaveOracle, IPoolDataProvider, IACLManager} from './AaveV3.sol';
import {ICollector} from './common/ICollector.sol';

library AaveV3Sepolia {
  // https://sepolia.etherscan.io/address/0x7EEb8582fE8f8B0982f02619A04F344893df48c0
  IPoolAddressesProvider internal constant POOL_ADDRESSES_PROVIDER =
    IPoolAddressesProvider(0x7EEb8582fE8f8B0982f02619A04F344893df48c0);

  // https://sepolia.etherscan.io/address/0x545a706a898E4a4a3Cf90AA69D231151C38603bc
  IPool internal constant POOL = IPool(0x545a706a898E4a4a3Cf90AA69D231151C38603bc);

  // https://sepolia.etherscan.io/address/0xC727DD0FA5F9f35e27a99fb056cBbA21B57c7D06
  IPoolConfigurator internal constant POOL_CONFIGURATOR =
    IPoolConfigurator(0xC727DD0FA5F9f35e27a99fb056cBbA21B57c7D06);

  // https://sepolia.etherscan.io/address/0xF2f6A516C211d0310f5D58b16599e5E05347dCdC
  IAaveOracle internal constant ORACLE = IAaveOracle(0xF2f6A516C211d0310f5D58b16599e5E05347dCdC);

  // https://sepolia.etherscan.io/address/0x0000000000000000000000000000000000000000
  address internal constant PRICE_ORACLE_SENTINEL = 0x0000000000000000000000000000000000000000;

  // https://sepolia.etherscan.io/address/0x17100C740957d7B40E9AF5ecbA5716D6cF92A9eb
  IPoolDataProvider internal constant AAVE_PROTOCOL_DATA_PROVIDER =
    IPoolDataProvider(0x17100C740957d7B40E9AF5ecbA5716D6cF92A9eb);

  // https://sepolia.etherscan.io/address/0x586F324807b147f7f43d21111ed607587aa4B59f
  IACLManager internal constant ACL_MANAGER =
    IACLManager(0x586F324807b147f7f43d21111ed607587aa4B59f);

  // https://sepolia.etherscan.io/address/0xcbeD65Db7E177D4875dDF5B67E13326A43a7B03f
  address internal constant ACL_ADMIN = 0xcbeD65Db7E177D4875dDF5B67E13326A43a7B03f;

  // https://sepolia.etherscan.io/address/0x22d4512557aa5a2F88AC9d505867218dB17a620A
  ICollector internal constant COLLECTOR = ICollector(0x22d4512557aa5a2F88AC9d505867218dB17a620A);

  // https://sepolia.etherscan.io/address/0x59554D7c5693425cE9a1fB7d4fe1B7FAC4a66074
  address internal constant DEFAULT_INCENTIVES_CONTROLLER =
    0x59554D7c5693425cE9a1fB7d4fe1B7FAC4a66074;

  // https://sepolia.etherscan.io/address/0x777885b1f73f38990b43a766Dd0aAdd30C7D41F8
  address internal constant DEFAULT_A_TOKEN_IMPL_REV_1 = 0x777885b1f73f38990b43a766Dd0aAdd30C7D41F8;

  // https://sepolia.etherscan.io/address/0x4beCf11dB5a9dE303E0D3961855fB4a50b9FF55B
  address internal constant DEFAULT_VARIABLE_DEBT_TOKEN_IMPL_REV_1 =
    0x4beCf11dB5a9dE303E0D3961855fB4a50b9FF55B;

  // https://sepolia.etherscan.io/address/0xa9a993275F308478f6C89438C23DdC91F210bc1B
  address internal constant DEFAULT_STABLE_DEBT_TOKEN_IMPL_REV_1 =
    0xa9a993275F308478f6C89438C23DdC91F210bc1B;

  // https://sepolia.etherscan.io/address/0x57A6Ecfc60A0c5A7C4E9813EFF1a87F857009CAB
  address internal constant EMISSION_MANAGER = 0x57A6Ecfc60A0c5A7C4E9813EFF1a87F857009CAB;

  // https://sepolia.etherscan.io/address/0xB653EC2fd50562d87EC15e1bECfAbeC7e318A5f1
  address internal constant FAUCET = 0xB653EC2fd50562d87EC15e1bECfAbeC7e318A5f1;

  // https://sepolia.etherscan.io/address/0x81C01ac70B1ee2BC281B3E6f73358e31dC2c83f0
  address internal constant UI_INCENTIVE_DATA_PROVIDER = 0x81C01ac70B1ee2BC281B3E6f73358e31dC2c83f0;

  // https://sepolia.etherscan.io/address/0xc9d35a9bC294fC01D6c21119D18f36edf07B2981
  address internal constant UI_POOL_DATA_PROVIDER = 0xc9d35a9bC294fC01D6c21119D18f36edf07B2981;

  // https://sepolia.etherscan.io/address/0x43f6FCB86aa9D6222362aD78bBda238Af87881A0
  address internal constant WALLET_BALANCE_PROVIDER = 0x43f6FCB86aa9D6222362aD78bBda238Af87881A0;

  // https://sepolia.etherscan.io/address/0x5398fAad146b27639613879BeB90Db546c089037
  address internal constant WETH_GATEWAY = 0x5398fAad146b27639613879BeB90Db546c089037;
}

library AaveV3SepoliaAssets {
  // https://sepolia.etherscan.io/address/0x6c0115846bEb8d1CD6b51DB72C5deE425deAD285
  address internal constant DAII_UNDERLYING = 0x6c0115846bEb8d1CD6b51DB72C5deE425deAD285;

  uint8 internal constant DAII_DECIMALS = 18;

  // https://sepolia.etherscan.io/address/0x73Ac7D205330B877284ba5E0fb3171B7fba57bA7
  address internal constant DAII_A_TOKEN = 0x73Ac7D205330B877284ba5E0fb3171B7fba57bA7;

  // https://sepolia.etherscan.io/address/0xd4Db0ae5946B5962d12E2F54152283B1ac9131ec
  address internal constant DAII_V_TOKEN = 0xd4Db0ae5946B5962d12E2F54152283B1ac9131ec;

  // https://sepolia.etherscan.io/address/0x024D6307dEC6718d4Df9e8a2536e84e8858d5C59
  address internal constant DAII_S_TOKEN = 0x024D6307dEC6718d4Df9e8a2536e84e8858d5C59;

  // https://sepolia.etherscan.io/address/0x7911d586c32f66E2Fe0474df287D221A2f1C88A8
  address internal constant DAII_ORACLE = 0x7911d586c32f66E2Fe0474df287D221A2f1C88A8;

  // https://sepolia.etherscan.io/address/0xdb11044CF27d2086c86771A0ebeA4dA129F637DF
  address internal constant DAII_INTEREST_RATE_STRATEGY =
    0xdb11044CF27d2086c86771A0ebeA4dA129F637DF;

  // https://sepolia.etherscan.io/address/0x76127399A0CafeDB59615A93A7ACF8552c1aEE4c
  address internal constant USDT_UNDERLYING = 0x76127399A0CafeDB59615A93A7ACF8552c1aEE4c;

  uint8 internal constant USDT_DECIMALS = 6;

  // https://sepolia.etherscan.io/address/0x7BB8b6Bf92a05a2FC16FaD5Ac467628C0F1F6D17
  address internal constant USDT_A_TOKEN = 0x7BB8b6Bf92a05a2FC16FaD5Ac467628C0F1F6D17;

  // https://sepolia.etherscan.io/address/0xEb285ff1bA91e2B7289710C34Aa4c13Da834d653
  address internal constant USDT_V_TOKEN = 0xEb285ff1bA91e2B7289710C34Aa4c13Da834d653;

  // https://sepolia.etherscan.io/address/0xEdf140e5cc85C6a27914c94020199628780b7F8b
  address internal constant USDT_S_TOKEN = 0xEdf140e5cc85C6a27914c94020199628780b7F8b;

  // https://sepolia.etherscan.io/address/0x14866185B1962B63C3Ea9E03Bc1da838bab34C19
  address internal constant USDT_ORACLE = 0x14866185B1962B63C3Ea9E03Bc1da838bab34C19;

  // https://sepolia.etherscan.io/address/0x7031c5B8bCdfD9a09D30c79a28243200Fe1D12a5
  address internal constant USDT_INTEREST_RATE_STRATEGY =
    0x7031c5B8bCdfD9a09D30c79a28243200Fe1D12a5;

  // https://sepolia.etherscan.io/address/0xE55a23aaFb3a712BFae5BE96E0f61C745dedf33C
  address internal constant WETH_UNDERLYING = 0xE55a23aaFb3a712BFae5BE96E0f61C745dedf33C;

  uint8 internal constant WETH_DECIMALS = 18;

  // https://sepolia.etherscan.io/address/0x55a53F2A9C7f9BC1ab01366e2802a1765C57Be13
  address internal constant WETH_A_TOKEN = 0x55a53F2A9C7f9BC1ab01366e2802a1765C57Be13;

  // https://sepolia.etherscan.io/address/0x44152e2a33AA0ed975f350e8b878fA084420EE69
  address internal constant WETH_V_TOKEN = 0x44152e2a33AA0ed975f350e8b878fA084420EE69;

  // https://sepolia.etherscan.io/address/0xc31dB5a33B423ECA6dE4bb4Eb137D899fE68171e
  address internal constant WETH_S_TOKEN = 0xc31dB5a33B423ECA6dE4bb4Eb137D899fE68171e;

  // https://sepolia.etherscan.io/address/0x694AA1769357215DE4FAC081bf1f309aDC325306
  address internal constant WETH_ORACLE = 0x694AA1769357215DE4FAC081bf1f309aDC325306;

  // https://sepolia.etherscan.io/address/0xcEd4C9E6D3730F4316884d956b16F30C49e4451f
  address internal constant WETH_INTEREST_RATE_STRATEGY =
    0xcEd4C9E6D3730F4316884d956b16F30C49e4451f;

  // https://sepolia.etherscan.io/address/0xAF48F7c5866c0Fd63492bAc0b7816c1933c4D43a
  address internal constant WBTC_UNDERLYING = 0xAF48F7c5866c0Fd63492bAc0b7816c1933c4D43a;

  uint8 internal constant WBTC_DECIMALS = 8;

  // https://sepolia.etherscan.io/address/0xdb808735103603BbeBe3aaafAcf9AC898F9e5712
  address internal constant WBTC_A_TOKEN = 0xdb808735103603BbeBe3aaafAcf9AC898F9e5712;

  // https://sepolia.etherscan.io/address/0x9567b6332745C32255B61c965B1EC42fc345C392
  address internal constant WBTC_V_TOKEN = 0x9567b6332745C32255B61c965B1EC42fc345C392;

  // https://sepolia.etherscan.io/address/0x88011A742CFb4eCC4E51d4835E7EBfeF67f82848
  address internal constant WBTC_S_TOKEN = 0x88011A742CFb4eCC4E51d4835E7EBfeF67f82848;

  // https://sepolia.etherscan.io/address/0x1b44F3514812d835EB1BDB0acB33d3fA3351Ee43
  address internal constant WBTC_ORACLE = 0x1b44F3514812d835EB1BDB0acB33d3fA3351Ee43;

  // https://sepolia.etherscan.io/address/0xDc34b169283ba59041e4Bcb93a1a4E8E85E48Cb8
  address internal constant WBTC_INTEREST_RATE_STRATEGY =
    0xDc34b169283ba59041e4Bcb93a1a4E8E85E48Cb8;
}

library AaveV3SepoliaEModes {
  uint8 internal constant NONE = 0;
}
